id: PDA816FF8
initial_creation_type: input
source_metadata:
  title: Thinley Norbu Rinpoche
  language: en
  description: 'Texts by Thinley Norbu Rinpoche or Dungsé Thinley Norbu (gdung sras
    phrin las nor bu, 1931–2011), who was the eldest son of Dudjom Rinpoche and a
    celebrated Nyingma teacher in his own right:'
  volume:
    4c619ee9d44d4f02a3e0f44d0928cc88:
      title: Prayer for the Long Life of Alak Zenkar Rinpoche, the Incarnation of
        Do Khyentsé Yeshé Dorjé
      parent: Long Life Prayers
created_at: '2022-03-01T01:47:08.699257'
last_modified_at: '2022-03-01T01:47:08.699263'
